# Generated by Django 5.0.9 on 2024-09-16 15:42

import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_video_path_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=video.models.video_file_path),
        ),
    ]
