# Generated by Django 5.0.9 on 2024-09-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_upload_progress_video_upload_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload_progress',
        ),
        migrations.RemoveField(
            model_name='video',
            name='upload_status',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
