# Generated by Django 5.0.7 on 2024-08-07 07:49

import django.utils.timezone
import keycloakAuth.keycloakAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to=keycloakAuth.keycloakAuth.models.user_profile_picture_file_path)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('updatedDate', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
