# Generated by Django 5.0.8 on 2024-08-27 06:56

import django.utils.timezone
import keycloakAuth.keycloakAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloakAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='createdDate',
            field=models.DateTimeField(db_column='createdDate', default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, db_column='profilePicture', null=True, upload_to=keycloakAuth.keycloakAuth.models.user_profile_picture_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updatedDate',
            field=models.DateTimeField(db_column='updatedDate', default=None, null=True),
        ),
    ]
